---
name: Publish Package on GitHub Container Registry

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    env:
      DOCKER_IMAGE: ${{ github.repository }}

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64 # linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
